285/HICS_Final_Chapter-master/cmps285HotelProject/HotelIntegratedComputerSystems/HotelIntegratedComputerSystems/Models/GridView/GridViewBuilding.cs
using System;
using System.Collections.Generic;
using HotelIntegratedComputerSystems.Models.Admin;
using HotelIntegratedComputerSystems.Models.Employees;

namespace HotelIntegratedComputerSystems.Models.GridView
{
    public class GridViewRooms
    {
        public List<RoomViewModel> RoomsList { get; set; }
        public List<string> DatesList { get; set; } 

    }
}

285/HICS_Final_Chapter-master/cmps285HotelProject/HotelIntegratedComputerSystems/HotelIntegratedComputerSystems/Models/GridView/GridViewRooms.cs
using System;
using System.Collections.Generic;
using HotelIntegratedComputerSystems.Models.Admin;
using HotelIntegratedComputerSystems.Models.Employees;

namespace HotelIntegratedComputerSystems.Models.GridView
{
    public class GridViewRooms
    {
        public List<RoomViewModel> RoomsList { get; set; }
        public List<string> DatesList { get; set; }
        public BookingViewModel BookingInfo { get; set; }
        public string RoomType { get; set; }
        public string HouseKeepingStatus { get; set; }
    }
}

285/HICS_Final_Chapter-master/cmps285HotelProject/HotelIntegratedComputerSystems/HotelIntegratedComputerSystems/Controllers/GridView/GridViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Net;
using System.Web.Mvc;
using HotelIntegratedComputerSystems.Models.Employees;
using HotelIntegratedComputerSystems.Services.Employee;
using HotelIntegratedComputerSystems.Services.GridViewService;
using HotelIntegratedComputerSystems.Controllers.Default;
using HotelIntegratedComputerSystems.Services.Admin;

namespace HotelIntegratedComputerSystems.Controllers.GridView
{
    public class GridViewController : BaseController
       
    {
        private  readonly GridViewServices _service = new GridViewServices();
        private readonly CustomerServices _customerService = new CustomerServices();
        private readonly BookingServices _bookingservice = new BookingServices();
        private readonly RoomServices _roomServices = new RoomServices();

        // GET: GridView
        public ActionResult Index()
        {
            if (Session["AccessLevel"] == null || int.Parse(Session["AccessLevel"].ToString()) == 1 || int.Parse(Session["AccessLevel"].ToString()) == 2) { return Redirect("~/NotAuthorized/Index"); }
            return View(_service.GetGridViewRooms(DateTime.Today, DateTime.Today.AddDays(6)));
        }

        [HttpPost]
        public ActionResult Index(DateTime startDate, DateTime endDate)
        {
            if (Session["AccessLevel"] == null || int.Parse(Session["AccessLevel"].ToString()) == 1 || int.Parse(Session["AccessLevel"].ToString()) == 2) { return Redirect("~/NotAuthorized/Index"); }
            return View(_service.GetGridViewRooms(startDate, endDate));

        }

        // GET: GridView/Details/5
        public ActionResult Details(int id)
        {
            if (Session["AccessLevel"] == null || int.Parse(Session["AccessLevel"].ToString()) == 1 || int.Parse(Session["AccessLevel"].ToString()) == 2) { return Redirect("~/NotAuthorized/Index"); }
            return View();
        }

        //public ActionResult Details()
        //{
        //    return View();
        //}

        // GET: GridView/Create
        public ActionResult NewCust()
        {
            if (Session["AccessLevel"] == null || int.Parse(Session["AccessLevel"].ToString()) == 1 || int.Parse(Session["AccessLevel"].ToString()) == 2) { return Redirect("~/NotAuthorized/Index"); }
            var actionResult = View();
            return actionResult;

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NewCust([Bind(Include = "Id,Name,Address,Phone,Email")] CustomersViewModel customersViewModel)
        {
            if (Session["AccessLevel"] == null || int.Parse(Session["AccessLevel"].ToString()) == 1 || int.Parse(Session["AccessLevel"].ToString()) == 2) { return Redirect("~/NotAuthorized/Index"); }
            if (!ModelState.IsValid) return View(customersViewModel);
            _customerService.CreateNewCustomer(customersViewModel);
            return RedirectToAction("Index");
        }

        // GET: Bookings/Create
        public ActionResult NewBook()
        {
            if (Session["AccessLevel"] == null || int.Parse(Session["AccessLevel"].ToString()) == 1 || int.Parse(Session["AccessLevel"].ToString()) == 2) { return Redirect("~/NotAuthorized/Index"); }
            BookingViewModel newBooking = new BookingViewModel();
            newBooking.customers = _bookingservice.loadCustomerNames();
            newBooking.RoomsList = _roomServices.GetRoomList();
            return View(newBooking);
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult NewBook([Bind(Include = "Id,CustomerId,RoomId,StartDate,EndDate,VolumeAdults,VolumeChildren,RoomNumber,FloorNumber,BuildingName,customers")] BookingViewModel bookingViewModel)
        {
            if (Session["AccessLevel"] == null || int.Parse(Session["AccessLevel"].ToString()) == 1 || int.Parse(Session["AccessLevel"].ToString()) == 2) { return Redirect("~/NotAuthorized/Index"); }
            if (!ModelState.IsValid) return View(bookingViewModel);
            _bookingservice.CreateNewBooking(bookingViewModel);

            return RedirectToAction("Index");
        }

        // POST: GridView/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            if (Session["AccessLevel"] == null || int.Parse(Session["AccessLevel"].ToString()) == 1 || int.Parse(Session["AccessLevel"].ToString()) == 2) { return Redirect("~/NotAuthorized/Index"); }

            try
            {
                // TODO: Add insert logic here
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: GridView/Edit/5
        public ActionResult Edit(int id)
        {
            if (Session["AccessLevel"] == null || int.Parse(Session["AccessLevel"].ToString()) == 1 || int.Parse(Session["AccessLevel"].ToString()) == 2) { return Redirect("~/NotAuthorized/Index"); }
            return View();
        }

        // POST: GridView/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            if (Session["AccessLevel"] == null || int.Parse(Session["AccessLevel"].ToString()) == 1 || int.Parse(Session["AccessLevel"].ToString()) == 2) { return Redirect("~/NotAuthorized/Index"); }
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: GridView/Delete/5
        public ActionResult Delete(int id)
        {
            if (Session["AccessLevel"] == null || int.Parse(Session["AccessLevel"].ToString()) == 1 || int.Parse(Session["AccessLevel"].ToString()) == 2) { return Redirect("~/NotAuthorized/Index"); }
            return View();
        }

        // POST: GridView/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            if (Session["AccessLevel"] == null || int.Parse(Session["AccessLevel"].ToString()) == 1 || int.Parse(Session["AccessLevel"].ToString()) == 2) { return Redirect("~/NotAuthorized/Index"); }
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

285/HICS_Final_Chapter-master/cmps285HotelProject/HotelIntegratedComputerSystems/HotelIntegratedComputerSystems/Views/GridView/Index.cshtml
@using HotelIntegratedComputerSystems.Models.Admin
@using HotelIntegratedComputerSystems.Models.GridView
@model HotelIntegratedComputerSystems.Models.GridView.GridViewRooms
@Scripts.Render("~/Scripts/OneFilterPerColumn.js")
<script src="~/Scripts/GridView.js"></script>

@{
    ViewBag.Title = "Index";
    Layout = "_LayoutGridView.cshtml";
}
<head>
    <title>Grid View</title>
    <link href="~/Content/GridViewStyleSheet.css" rel="stylesheet" />
</head>

<h2></h2>
<div class="col-lg-2 col-md-2 col-sm-2">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Filters</h3>
        </div>
        <div class="panel2">
            <input type="text" id="myInput1" onkeyup="filterFunctionColumn5('dev-table', 'myInput1', 'myInput2', 'myInput3', 'myInput4', 'myInput5', 'myInput6', 'myInput7')" class="form-control2 " data-action="filter" placeholder="Filter Building" />
            <input type="text" id="myInput2" onkeyup="filterFunctionColumn5('dev-table', 'myInput1', 'myInput2', 'myInput3', 'myInput4', 'myInput5', 'myInput6', 'myInput7')" class="form-control2" data-action="filter" placeholder="Filter Floor" />
            <input type="text" id="myInput3" onkeyup="filterFunctionColumn5('dev-table', 'myInput1', 'myInput2', 'myInput3', 'myInput4', 'myInput5', 'myInput6', 'myInput7')" class="form-control2" data-action="filter" placeholder="Filter Room" />
            <input type="text" id="myInput4" onkeyup="filterFunctionColumn5('dev-table', 'myInput1', 'myInput2', 'myInput3', 'myInput4', 'myInput5', 'myInput6', 'myInput7')" class="form-control2" data-action="filter" placeholder="Filter Clean Status" />
            <input type="text" id="myInput5" onkeyup="filterFunctionColumn5('dev-table', 'myInput1', 'myInput2', 'myInput3', 'myInput4', 'myInput5', 'myInput6', 'myInput7')" class="form-control2" data-action="filter" placeholder="Filter Room Type" />

            @using (Html.BeginForm())
            {
                @Html.Label("From:")
                <input id="startDate" type="date" name="startDate" class="form-control2 col-lg-2" required />
                @Html.Label("To:")
                <input id="endDate" type="date" name="endDate" class="form-control2" required />

                <input type="submit" value="Submit Date Range" class="form-control2" />
            }
            @Html.ActionLink("Add Customer", "NewCust", null, htmlAttributes: new { @class = "btn btn-default" })
            @Html.ActionLink("Add Booking", "NewBook", null, htmlAttributes: new { @class = "btn btn-default" })
        </div>
    </div>
</div>


<div class="col-lg-10 col-md-10 col-sm-10">
    <div class="grid-panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Grid View</h3>
        </div>
        <div class="panel1">
            <table class="table table-bordered" id="dev-table">
                <thead>
                    <tr>
                        <th>
                            Building
                        </th>
                        <th>
                            Floor #
                        </th>
                        <th>
                            Room Name
                        </th>
                        <th>
                            Clean Status
                        </th>
                        <th>
                            Room Type
                        </th>
                        @foreach (var item in Model.DatesList)
                        {
                            <th>
                                @Html.DisplayFor(modelItem => item)
                            </th>

                        }
                    </tr>
                </thead>
                <tbody>
                    @foreach (var currentRoom in Model.RoomsList)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => currentRoom.BuildingName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => currentRoom.FloorNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => currentRoom.RoomNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => currentRoom.HouseKeepingStatus)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => currentRoom.RoomType)
                            </td>
                            @foreach (var currentBooking in currentRoom.BookingsList)
                            {
                                if (currentBooking.CustomerName != null)
                                {
                                    <td class="grid-cell-occupied">
                                        @*<div><button id="customerNameSend" onclick="pushValuesToEditorExists(this.parentElement.parentElement, recieveBuilding, recieveFloor,
                                                recieveRoom, recieveHouseKeeping, recieveRoomType, recieveCustomer, recieveCreateEditStartDate, recieveCreateEditEndDate, customerNameSend,
                                                StartDateSend, EndDateSend, BuildingSend, FloorSend, RoomSend, RoomTypeSend, HousekeepingSend)"
                                                >@Html.DisplayFor(modelItem => currentBooking.CustomerName)</button></div>*@

                                            @Html.DisplayFor(modelItem => currentBooking.CustomerName)
                                               
                                                

                                        <div style="display:none">
                                            <div id="StartDateSend">@Html.DisplayFor(modelItem => currentBooking.StartDate)</div>
                                            <div id="EndDateSend">@Html.DisplayFor(modelItem => currentBooking.EndDate)</div>
                                            <div id="BuildingSend">@Html.DisplayFor(modelItem => currentBooking.BuildingName)</div>
                                            <div id="FloorSend">@Html.DisplayFor(modelItem => currentBooking.FloorNumber)</div>
                                            <div id="RoomSend">@Html.DisplayFor(modelItem => currentBooking.RoomNumber)</div>
                                            <div id="RoomTypeSend">@Html.DisplayFor(modelItem => currentBooking.RoomType)</div>
                                            <div id="HousekeepingSend">@Html.DisplayFor(modelItem => currentBooking.HouseKeepingStatus)</div>
                                        </div>

                                    </td>
                                }
                                else
                                {
                                    <td onclick="pushValuesToEditorNonExistant" class="grid-cell-vacant">

                                            Vacant

                                    </td>
                                }
                            }
                        </tr>

                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="col-lg-12 col-md-10 col-sm-10" hidden>
    <div class="info-panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Booking Information</h3>
        </div>
        <div class="info-btn-container">
                @Html.ActionLink("Edit Booking", "Create", null, htmlAttributes: new { @class = "btn btn-default" })

                @Html.ActionLink("New Booking", "Create", null, htmlAttributes: new { @class = "btn btn-default" })          
        </div>
        <div class="info-info-container">
            <table>
                <tr>
                    <td>
                        @Html.Label("Building")
                        <input id="recieveBuilding" type="Text" name="Building" class="form-control2 col-lg-2" required />
                    </td>
                    <td>
                        @Html.Label("Floor")
                        <input id="recieveFloor" type="Text" name="Floor" class="form-control2 col-lg-2" required />
                    </td>
                    <td>
                        @Html.Label("Room")
                        <input id="recieveRoom" type="Text" name="Room" class="form-control2 col-lg-2" required />
                    </td>
                    <td>
                        @Html.Label("Housekeeping")
                        <input id="recieveHouseKeeping" type="Text" name="Housekeeping" class="form-control2 col-lg-2" required />
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.Label("Room Type")
                        <input id="recieveRoomType" type="Text" name="RoomType" class="form-control2 col-lg-2" required />
                    </td>
                    <td>
                        @Html.Label("Customer Name")
                        <input id="recieveCustomer" type="Text" name="CustomerName" class="form-control2 col-lg-2" required />
                    </td>
                    <td>
                        @Html.Label("Start Date")
                        <input id="recieveCreateEditStartDate" type="Text" name="CreateEditStartDate" class="form-control2 col-lg-2" required />
                    </td>
                    <td>
                        @Html.Label("End Date")
                        <input id="recieveCreateEditEndDate" type="Text" name="CreateEditEndDate" class="form-control2" required />
                    </td>

                </tr>
            </table>
        </div>
    </div>
</div>

285/HICS_Final_Chapter-master/cmps285HotelProject/HotelIntegratedComputerSystems/HotelIntegratedComputerSystems/Views/GridView/NewCust.cshtml
@model HotelIntegratedComputerSystems.Models.Employees.CustomersViewModel

@{
    ViewBag.Title = "Create";
}

<h2></h2>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">Create</h3>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

285/HICS_Final_Chapter-master/cmps285HotelProject/HotelIntegratedComputerSystems/HotelIntegratedComputerSystems/Views/GridView/_LayoutGridView.cshtml
@using HotelIntegratedComputerSystems.Controllers.Default
@{
    var userName = "";
    var userRank = 0;
    var userLoggedIn = false;


    if (Session["Name"] != null)
    {
        userName = Session["Name"].ToString();
    }

    if (Session["AccessLevel"] != null)
    {
        userRank = int.Parse(Session["AccessLevel"].ToString());
    }

    if (Session["IsLoggedOn"] != null)
    {
        userLoggedIn = bool.Parse(Session["IsLoggedOn"].ToString());
    }
}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - H.I.C.S.</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/GoogleAuth.js")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <!-- sign in code -->
    <meta name="google-signin-client_id" content="774525732284-lpuok1q2o879p2ehg56k5e35q0ctnp22.apps.googleusercontent.com">
    <script src="https://apis.google.com/js/platform.js" async defer></script>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("H.I.C.S.", "Index", "GridView", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <uldiv class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @if (userRank == 4 || userRank == 5)
                        {
                             <!--ADMIN TAB-->
                            <div class="dropdown">
                                <button class="btn btn-primary dropdown-toggle media" type="button" data-toggle="dropdown">Admin <span class="caret"></span></button>
                                <ul class="dropdown-menu">
                                    <li>Rooms</li>
                                    <li>@Html.ActionLink("Buildings", "Index", "Buildings")</li>
                                    <li>@Html.ActionLink("Rooms", "Index", "Rooms")</li>
                                    <li>@Html.ActionLink("Room Types", "Index", "RoomTypes")</li>
                                    <li>Employees</li>
                                    <li>@Html.ActionLink("Employees", "Index", "Employees")</li>
                                    <li>@Html.ActionLink("Employee Types", "Index", "EmployeeTypes")</li>
                                    <li>@Html.ActionLink("Employee Shifts", "Index", "EmployeeShifts")</li>
                                    <li>Expences</li>
                                    <li>@Html.ActionLink("Expense Types", "Index", "ExpenseTypes")</li>
                                    <li>@Html.ActionLink("Expenses", "Index", "Expenses")</li>

                                    <li>Maintenance</li>
                                    <li>@Html.ActionLink("Maintenance Types", "Index", "MaintenanceTypes")</li>
                                    <li>@Html.ActionLink("Maintenance Logs", "Index", "MaintenanceLogs")</li>

                                </ul>
                            </div>

                        }
                    </li> <!--ADMIN TAB-->
                    <li>
                        @if (userRank == 3 || userRank == 4 || userRank == 5)
                        {
                            <!--Employee TAB-->
                            <div class="dropdown">
                                <button class="btn btn-primary dropdown-toggle media" type="button" data-toggle="dropdown">Front Desk <span class="caret"></span></button>
                                <ul class="dropdown-menu">
                                    <li>Customers</li>
                                    <li>@Html.ActionLink("GridView", "Index", "GridView")</li>
                                    <li>@Html.ActionLink("Customers", "Index", "Customers")</li>
                                    <li>@Html.ActionLink("Expenses", "Index", "Expenses")</li>
                                    <li>@Html.ActionLink("Check-In/Out", "Index", "Transactions")</li>

                                </ul>
                            </div>
                        }
                    </li><!--Employee TAB-->
                    <li>
                        @if (userRank == 1 || userRank == 4 || userRank == 5)
                        {
                            <!--HouseKeeping-->
                            <div class="dropdown">
                                <button class="btn btn-primary dropdown-toggle media" type="button" data-toggle="dropdown">Maid Service <span class="caret"></span></button>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Housekeeping", "Index", "HouseKeeping")</li>
                                </ul>
                            </div>
                        }
                    </li><!--HouseKeeping TAB-->
                    <li>
                        @if (userRank == 2 || userRank == 4 || userRank == 5)
                        {
                            <!--Maintenance TAB-->
                            <div class="dropdown">
                                <button class="btn btn-primary dropdown-toggle media" type="button" data-toggle="dropdown">Maintenance <span class="caret"></span></button>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Maintenance Logs", "Index", "MaintenanceLogs")</li>
                                </ul>
                            </div>
                        }
                    </li><!--Maintenance TAB-->
                </ul>
                @if (userLoggedIn)
                {
                        <!-- this must never be deleted. It lets us get the user logged in and sign their token out. Keeps user from "log-in log-out log-in log-out ....."-->
                    <div class="g-signin2" data-height="0" data-width="0" data-longtitle="true" style="visibility: hidden"></div>

                        <div class="dropdown navbar-right">
                            <button class="btn btn-primary dropdown-toggle media" type="button" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span>@Html.DisplayName(" " + userName) <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Index", "ClockInClockOut")"><span class="glyphicon glyphicon-credit-card"></span> Clock-In/Out</a></li>
                                <li><a href="#" onclick="signOut()"><span class="glyphicon glyphicon-log-out"></span> Sign Out</a></li>
                            </ul>
                        </div>
                }
                else
                {
                    <div class="dropdown navbar-right">
                        <div class="g-signin2"
                             data-height="40"
                             data-width="240"
                             data-longtitle="true"
                             data-onsuccess="onSignIn">
                        </div>
                    </div>
                }
                </>
        </div>
    </div>

    <div class="grid-container body-content">
        <h2></h2>
        @RenderBody()
        <div class="footer navbar-fixed-bottom">
            <footer class="text-muted navbar-inverse footer-texts">
                <span class="navbar-right">
                    &copy; @DateTime.Now.Year - H.I.C.S.
                </span>

                @Html.MvcSiteMap().SiteMapPath()

            </footer>

        </div>
    </div>
</body>

</html>